name: Test Release Workflow

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Test version'
        required: true
        default: 'v2.2.1'

jobs:
  test:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
      - name: Test output
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref name: ${{ github.ref_name }}"
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Version from input: ${{ github.event.inputs.version }}"
          else
            echo "Version from ref: ${{ github.ref_name }}"
          fi